// Glasswork decision + custody graph — load into Neo4j / AuraDB
// Usage: cypher-shell < decision_graph.cypher   (or paste into Neo4j Browser)
CREATE CONSTRAINT IF NOT EXISTS FOR (m:Model) REQUIRE m.id IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (d:Doc) REQUIRE d.id IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (r:Run) REQUIRE r.id IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (c:CustodyRoot) REQUIRE c.model_id IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (x:Decision) REQUIRE x.id IS UNIQUE;
MERGE (m:Model {id:"meta-llama/llama-3.2-1b-instruct"}) SET m.params_b=1, m.tier="small", m.family="llama", m.recall=0.5, m.passes=false, m.is_pick=false;
MERGE (m:Model {id:"meta-llama/llama-3.2-3b-instruct"}) SET m.params_b=3, m.tier="small", m.family="llama", m.recall=0.6875, m.passes=false, m.is_pick=false;
MERGE (m:Model {id:"meta-llama/llama-3.1-8b-instruct"}) SET m.params_b=8, m.tier="small", m.family="llama", m.recall=0.6875, m.passes=false, m.is_pick=false;
MERGE (m:Model {id:"qwen/qwen3-8b"}) SET m.params_b=8, m.tier="small", m.family="qwen", m.recall=0.6875, m.passes=false, m.is_pick=false;
MERGE (m:Model {id:"qwen/qwen3-14b"}) SET m.params_b=14, m.tier="mid", m.family="qwen", m.recall=0.6875, m.passes=false, m.is_pick=false;
MERGE (m:Model {id:"microsoft/phi-4"}) SET m.params_b=14, m.tier="mid", m.family="phi", m.recall=0.6875, m.passes=false, m.is_pick=false;
MERGE (m:Model {id:"openai/gpt-oss-20b"}) SET m.params_b=20, m.tier="mid", m.family="gpt-oss", m.recall=0.6875, m.passes=false, m.is_pick=false;
MERGE (m:Model {id:"google/gemma-3-27b-it"}) SET m.params_b=27, m.tier="mid", m.family="gemma", m.recall=0.9375, m.passes=true, m.is_pick=true;
MERGE (m:Model {id:"qwen/qwen3-32b"}) SET m.params_b=32, m.tier="mid", m.family="qwen", m.recall=0.75, m.passes=true, m.is_pick=false;
MERGE (m:Model {id:"meta-llama/llama-3.3-70b-instruct"}) SET m.params_b=70, m.tier="large", m.family="llama", m.recall=0.4375, m.passes=false, m.is_pick=false;
MERGE (m:Model {id:"openai/gpt-oss-120b"}) SET m.params_b=120, m.tier="large", m.family="gpt-oss", m.recall=0.6875, m.passes=false, m.is_pick=false;
MERGE (m:Model {id:"qwen/qwen3-235b-a22b-2507"}) SET m.params_b=235, m.tier="large", m.family="qwen", m.recall=0.875, m.passes=true, m.is_pick=false;
MERGE (d:Doc {id:"doc-photosynthesis"}) SET d.title="Photosynthesis (biology primer)", d.gold_claims=8;
MERGE (d:Doc {id:"doc-water-cycle"}) SET d.title="The water cycle (earth science primer)", d.gold_claims=8;
MERGE (r:Run {id:"meta_llama_llama_3_3_70b_instruct__doc-water-cycle"}) SET r.precision=0, r.recall=0, r.passes=false, r.parse_status="invalid_json";
MATCH (r:Run {id:"meta_llama_llama_3_3_70b_instruct__doc-water-cycle"}),(m:Model {id:"meta-llama/llama-3.3-70b-instruct"}) MERGE (r)-[:OF_MODEL]->(m);
MATCH (r:Run {id:"meta_llama_llama_3_3_70b_instruct__doc-water-cycle"}),(d:Doc {id:"doc-water-cycle"}) MERGE (r)-[:ON_DOC]->(d);
MERGE (r:Run {id:"meta_llama_llama_3_2_1b_instruct__doc-photosynthesis"}) SET r.precision=1, r.recall=0.625, r.passes=false, r.parse_status="ok";
MATCH (r:Run {id:"meta_llama_llama_3_2_1b_instruct__doc-photosynthesis"}),(m:Model {id:"meta-llama/llama-3.2-1b-instruct"}) MERGE (r)-[:OF_MODEL]->(m);
MATCH (r:Run {id:"meta_llama_llama_3_2_1b_instruct__doc-photosynthesis"}),(d:Doc {id:"doc-photosynthesis"}) MERGE (r)-[:ON_DOC]->(d);
MERGE (r:Run {id:"qwen_qwen3_8b__doc-photosynthesis"}) SET r.precision=1, r.recall=0.625, r.passes=false, r.parse_status="ok";
MATCH (r:Run {id:"qwen_qwen3_8b__doc-photosynthesis"}),(m:Model {id:"qwen/qwen3-8b"}) MERGE (r)-[:OF_MODEL]->(m);
MATCH (r:Run {id:"qwen_qwen3_8b__doc-photosynthesis"}),(d:Doc {id:"doc-photosynthesis"}) MERGE (r)-[:ON_DOC]->(d);
MERGE (r:Run {id:"meta_llama_llama_3_2_1b_instruct__doc-water-cycle"}) SET r.precision=1, r.recall=0.375, r.passes=false, r.parse_status="ok";
MATCH (r:Run {id:"meta_llama_llama_3_2_1b_instruct__doc-water-cycle"}),(m:Model {id:"meta-llama/llama-3.2-1b-instruct"}) MERGE (r)-[:OF_MODEL]->(m);
MATCH (r:Run {id:"meta_llama_llama_3_2_1b_instruct__doc-water-cycle"}),(d:Doc {id:"doc-water-cycle"}) MERGE (r)-[:ON_DOC]->(d);
MERGE (r:Run {id:"qwen_qwen3_8b__doc-water-cycle"}) SET r.precision=1, r.recall=0.75, r.passes=true, r.parse_status="ok";
MATCH (r:Run {id:"qwen_qwen3_8b__doc-water-cycle"}),(m:Model {id:"qwen/qwen3-8b"}) MERGE (r)-[:OF_MODEL]->(m);
MATCH (r:Run {id:"qwen_qwen3_8b__doc-water-cycle"}),(d:Doc {id:"doc-water-cycle"}) MERGE (r)-[:ON_DOC]->(d);
MERGE (r:Run {id:"meta_llama_llama_3_1_8b_instruct__doc-water-cycle"}) SET r.precision=1, r.recall=0.75, r.passes=true, r.parse_status="ok";
MATCH (r:Run {id:"meta_llama_llama_3_1_8b_instruct__doc-water-cycle"}),(m:Model {id:"meta-llama/llama-3.1-8b-instruct"}) MERGE (r)-[:OF_MODEL]->(m);
MATCH (r:Run {id:"meta_llama_llama_3_1_8b_instruct__doc-water-cycle"}),(d:Doc {id:"doc-water-cycle"}) MERGE (r)-[:ON_DOC]->(d);
MERGE (r:Run {id:"meta_llama_llama_3_1_8b_instruct__doc-photosynthesis"}) SET r.precision=1, r.recall=0.625, r.passes=false, r.parse_status="ok";
MATCH (r:Run {id:"meta_llama_llama_3_1_8b_instruct__doc-photosynthesis"}),(m:Model {id:"meta-llama/llama-3.1-8b-instruct"}) MERGE (r)-[:OF_MODEL]->(m);
MATCH (r:Run {id:"meta_llama_llama_3_1_8b_instruct__doc-photosynthesis"}),(d:Doc {id:"doc-photosynthesis"}) MERGE (r)-[:ON_DOC]->(d);
MERGE (r:Run {id:"meta_llama_llama_3_2_3b_instruct__doc-photosynthesis"}) SET r.precision=1, r.recall=0.625, r.passes=false, r.parse_status="ok";
MATCH (r:Run {id:"meta_llama_llama_3_2_3b_instruct__doc-photosynthesis"}),(m:Model {id:"meta-llama/llama-3.2-3b-instruct"}) MERGE (r)-[:OF_MODEL]->(m);
MATCH (r:Run {id:"meta_llama_llama_3_2_3b_instruct__doc-photosynthesis"}),(d:Doc {id:"doc-photosynthesis"}) MERGE (r)-[:ON_DOC]->(d);
MERGE (r:Run {id:"openai_gpt_oss_20b__doc-photosynthesis"}) SET r.precision=1, r.recall=0.625, r.passes=false, r.parse_status="ok";
MATCH (r:Run {id:"openai_gpt_oss_20b__doc-photosynthesis"}),(m:Model {id:"openai/gpt-oss-20b"}) MERGE (r)-[:OF_MODEL]->(m);
MATCH (r:Run {id:"openai_gpt_oss_20b__doc-photosynthesis"}),(d:Doc {id:"doc-photosynthesis"}) MERGE (r)-[:ON_DOC]->(d);
MERGE (r:Run {id:"meta_llama_llama_3_2_3b_instruct__doc-water-cycle"}) SET r.precision=1, r.recall=0.75, r.passes=true, r.parse_status="ok";
MATCH (r:Run {id:"meta_llama_llama_3_2_3b_instruct__doc-water-cycle"}),(m:Model {id:"meta-llama/llama-3.2-3b-instruct"}) MERGE (r)-[:OF_MODEL]->(m);
MATCH (r:Run {id:"meta_llama_llama_3_2_3b_instruct__doc-water-cycle"}),(d:Doc {id:"doc-water-cycle"}) MERGE (r)-[:ON_DOC]->(d);
MERGE (r:Run {id:"openai_gpt_oss_20b__doc-water-cycle"}) SET r.precision=1, r.recall=0.75, r.passes=true, r.parse_status="ok";
MATCH (r:Run {id:"openai_gpt_oss_20b__doc-water-cycle"}),(m:Model {id:"openai/gpt-oss-20b"}) MERGE (r)-[:OF_MODEL]->(m);
MATCH (r:Run {id:"openai_gpt_oss_20b__doc-water-cycle"}),(d:Doc {id:"doc-water-cycle"}) MERGE (r)-[:ON_DOC]->(d);
MERGE (r:Run {id:"microsoft_phi_4__doc-water-cycle"}) SET r.precision=1, r.recall=0.75, r.passes=true, r.parse_status="ok";
MATCH (r:Run {id:"microsoft_phi_4__doc-water-cycle"}),(m:Model {id:"microsoft/phi-4"}) MERGE (r)-[:OF_MODEL]->(m);
MATCH (r:Run {id:"microsoft_phi_4__doc-water-cycle"}),(d:Doc {id:"doc-water-cycle"}) MERGE (r)-[:ON_DOC]->(d);
MERGE (r:Run {id:"openai_gpt_oss_120b__doc-photosynthesis"}) SET r.precision=1, r.recall=0.625, r.passes=false, r.parse_status="ok";
MATCH (r:Run {id:"openai_gpt_oss_120b__doc-photosynthesis"}),(m:Model {id:"openai/gpt-oss-120b"}) MERGE (r)-[:OF_MODEL]->(m);
MATCH (r:Run {id:"openai_gpt_oss_120b__doc-photosynthesis"}),(d:Doc {id:"doc-photosynthesis"}) MERGE (r)-[:ON_DOC]->(d);
MERGE (r:Run {id:"qwen_qwen3_14b__doc-photosynthesis"}) SET r.precision=1, r.recall=0.625, r.passes=false, r.parse_status="ok";
MATCH (r:Run {id:"qwen_qwen3_14b__doc-photosynthesis"}),(m:Model {id:"qwen/qwen3-14b"}) MERGE (r)-[:OF_MODEL]->(m);
MATCH (r:Run {id:"qwen_qwen3_14b__doc-photosynthesis"}),(d:Doc {id:"doc-photosynthesis"}) MERGE (r)-[:ON_DOC]->(d);
MERGE (r:Run {id:"google_gemma_3_27b_it__doc-photosynthesis"}) SET r.precision=1, r.recall=1, r.passes=true, r.parse_status="ok";
MATCH (r:Run {id:"google_gemma_3_27b_it__doc-photosynthesis"}),(m:Model {id:"google/gemma-3-27b-it"}) MERGE (r)-[:OF_MODEL]->(m);
MATCH (r:Run {id:"google_gemma_3_27b_it__doc-photosynthesis"}),(d:Doc {id:"doc-photosynthesis"}) MERGE (r)-[:ON_DOC]->(d);
MERGE (r:Run {id:"qwen_qwen3_14b__doc-water-cycle"}) SET r.precision=1, r.recall=0.75, r.passes=true, r.parse_status="ok";
MATCH (r:Run {id:"qwen_qwen3_14b__doc-water-cycle"}),(m:Model {id:"qwen/qwen3-14b"}) MERGE (r)-[:OF_MODEL]->(m);
MATCH (r:Run {id:"qwen_qwen3_14b__doc-water-cycle"}),(d:Doc {id:"doc-water-cycle"}) MERGE (r)-[:ON_DOC]->(d);
MERGE (r:Run {id:"google_gemma_3_27b_it__doc-water-cycle"}) SET r.precision=1, r.recall=0.875, r.passes=true, r.parse_status="ok";
MATCH (r:Run {id:"google_gemma_3_27b_it__doc-water-cycle"}),(m:Model {id:"google/gemma-3-27b-it"}) MERGE (r)-[:OF_MODEL]->(m);
MATCH (r:Run {id:"google_gemma_3_27b_it__doc-water-cycle"}),(d:Doc {id:"doc-water-cycle"}) MERGE (r)-[:ON_DOC]->(d);
MERGE (r:Run {id:"microsoft_phi_4__doc-photosynthesis"}) SET r.precision=1, r.recall=0.625, r.passes=false, r.parse_status="ok";
MATCH (r:Run {id:"microsoft_phi_4__doc-photosynthesis"}),(m:Model {id:"microsoft/phi-4"}) MERGE (r)-[:OF_MODEL]->(m);
MATCH (r:Run {id:"microsoft_phi_4__doc-photosynthesis"}),(d:Doc {id:"doc-photosynthesis"}) MERGE (r)-[:ON_DOC]->(d);
MERGE (r:Run {id:"qwen_qwen3_32b__doc-water-cycle"}) SET r.precision=1, r.recall=0.75, r.passes=true, r.parse_status="ok";
MATCH (r:Run {id:"qwen_qwen3_32b__doc-water-cycle"}),(m:Model {id:"qwen/qwen3-32b"}) MERGE (r)-[:OF_MODEL]->(m);
MATCH (r:Run {id:"qwen_qwen3_32b__doc-water-cycle"}),(d:Doc {id:"doc-water-cycle"}) MERGE (r)-[:ON_DOC]->(d);
MERGE (r:Run {id:"qwen_qwen3_32b__doc-photosynthesis"}) SET r.precision=1, r.recall=0.75, r.passes=true, r.parse_status="ok";
MATCH (r:Run {id:"qwen_qwen3_32b__doc-photosynthesis"}),(m:Model {id:"qwen/qwen3-32b"}) MERGE (r)-[:OF_MODEL]->(m);
MATCH (r:Run {id:"qwen_qwen3_32b__doc-photosynthesis"}),(d:Doc {id:"doc-photosynthesis"}) MERGE (r)-[:ON_DOC]->(d);
MERGE (r:Run {id:"meta_llama_llama_3_3_70b_instruct__doc-photosynthesis"}) SET r.precision=1, r.recall=0.875, r.passes=true, r.parse_status="ok";
MATCH (r:Run {id:"meta_llama_llama_3_3_70b_instruct__doc-photosynthesis"}),(m:Model {id:"meta-llama/llama-3.3-70b-instruct"}) MERGE (r)-[:OF_MODEL]->(m);
MATCH (r:Run {id:"meta_llama_llama_3_3_70b_instruct__doc-photosynthesis"}),(d:Doc {id:"doc-photosynthesis"}) MERGE (r)-[:ON_DOC]->(d);
MERGE (r:Run {id:"qwen_qwen3_235b_a22b_2507__doc-water-cycle"}) SET r.precision=1, r.recall=0.875, r.passes=true, r.parse_status="ok";
MATCH (r:Run {id:"qwen_qwen3_235b_a22b_2507__doc-water-cycle"}),(m:Model {id:"qwen/qwen3-235b-a22b-2507"}) MERGE (r)-[:OF_MODEL]->(m);
MATCH (r:Run {id:"qwen_qwen3_235b_a22b_2507__doc-water-cycle"}),(d:Doc {id:"doc-water-cycle"}) MERGE (r)-[:ON_DOC]->(d);
MERGE (r:Run {id:"openai_gpt_oss_120b__doc-water-cycle"}) SET r.precision=1, r.recall=0.75, r.passes=true, r.parse_status="ok";
MATCH (r:Run {id:"openai_gpt_oss_120b__doc-water-cycle"}),(m:Model {id:"openai/gpt-oss-120b"}) MERGE (r)-[:OF_MODEL]->(m);
MATCH (r:Run {id:"openai_gpt_oss_120b__doc-water-cycle"}),(d:Doc {id:"doc-water-cycle"}) MERGE (r)-[:ON_DOC]->(d);
MERGE (r:Run {id:"qwen_qwen3_235b_a22b_2507__doc-photosynthesis"}) SET r.precision=1, r.recall=0.875, r.passes=true, r.parse_status="ok";
MATCH (r:Run {id:"qwen_qwen3_235b_a22b_2507__doc-photosynthesis"}),(m:Model {id:"qwen/qwen3-235b-a22b-2507"}) MERGE (r)-[:OF_MODEL]->(m);
MATCH (r:Run {id:"qwen_qwen3_235b_a22b_2507__doc-photosynthesis"}),(d:Doc {id:"doc-photosynthesis"}) MERGE (r)-[:ON_DOC]->(d);
MERGE (c:CustodyRoot {model_id:"meta-llama/llama-3.2-1b-instruct"}) SET c.root_sha256="c950ef0f553019b3df6872170eade03bbea92c4d61553ef9fe4ed5acf3803b90", c.tampered=false, c.leaf_count=4;
MATCH (m:Model {id:"meta-llama/llama-3.2-1b-instruct"}),(c:CustodyRoot {model_id:"meta-llama/llama-3.2-1b-instruct"}) MERGE (m)-[:HAS_CUSTODY]->(c);
MERGE (c:CustodyRoot {model_id:"meta-llama/llama-3.2-3b-instruct"}) SET c.root_sha256="68a0758543333c09fa8e4919e1739f02c74bd94c1b4d7b046e801550ec82f4ee", c.tampered=false, c.leaf_count=4;
MATCH (m:Model {id:"meta-llama/llama-3.2-3b-instruct"}),(c:CustodyRoot {model_id:"meta-llama/llama-3.2-3b-instruct"}) MERGE (m)-[:HAS_CUSTODY]->(c);
MERGE (c:CustodyRoot {model_id:"meta-llama/llama-3.1-8b-instruct"}) SET c.root_sha256="a8cfd4310058715c51ad389738e4a162f940985b4268b57bdfb21c41942c05e0", c.tampered=false, c.leaf_count=4;
MATCH (m:Model {id:"meta-llama/llama-3.1-8b-instruct"}),(c:CustodyRoot {model_id:"meta-llama/llama-3.1-8b-instruct"}) MERGE (m)-[:HAS_CUSTODY]->(c);
MERGE (c:CustodyRoot {model_id:"qwen/qwen3-8b"}) SET c.root_sha256="9f3f72e1d2346aeae0b5fb02b302cb05b83c26510b32d42dc632c29debd2979e", c.tampered=false, c.leaf_count=4;
MATCH (m:Model {id:"qwen/qwen3-8b"}),(c:CustodyRoot {model_id:"qwen/qwen3-8b"}) MERGE (m)-[:HAS_CUSTODY]->(c);
MERGE (c:CustodyRoot {model_id:"openai/gpt-oss-20b"}) SET c.root_sha256="4d7587813c05f55b08f01a8993b702469091150c95a808889d4d02a5912b1b50", c.tampered=true, c.leaf_count=4;
MATCH (m:Model {id:"openai/gpt-oss-20b"}),(c:CustodyRoot {model_id:"openai/gpt-oss-20b"}) MERGE (m)-[:HAS_CUSTODY]->(c);
MERGE (c:CustodyRoot {model_id:"microsoft/phi-4"}) SET c.root_sha256="0e9b3c2be5108f450c25eb3f1bdb4c75dc25e1063f9d6cdbbe98b12a1ba3cac9", c.tampered=false, c.leaf_count=4;
MATCH (m:Model {id:"microsoft/phi-4"}),(c:CustodyRoot {model_id:"microsoft/phi-4"}) MERGE (m)-[:HAS_CUSTODY]->(c);
MERGE (c:CustodyRoot {model_id:"qwen/qwen3-14b"}) SET c.root_sha256="81d1fa9399fdbe7121210dc748dc888370e38180156667414ae7ed3c9ecfe231", c.tampered=false, c.leaf_count=4;
MATCH (m:Model {id:"qwen/qwen3-14b"}),(c:CustodyRoot {model_id:"qwen/qwen3-14b"}) MERGE (m)-[:HAS_CUSTODY]->(c);
MERGE (c:CustodyRoot {model_id:"google/gemma-3-27b-it"}) SET c.root_sha256="f4feaf176782b9aa2732d76b3c0f673c6ff68b524e25e59b7952491194e63136", c.tampered=false, c.leaf_count=4;
MATCH (m:Model {id:"google/gemma-3-27b-it"}),(c:CustodyRoot {model_id:"google/gemma-3-27b-it"}) MERGE (m)-[:HAS_CUSTODY]->(c);
MERGE (c:CustodyRoot {model_id:"qwen/qwen3-32b"}) SET c.root_sha256="f0d3f86a416d45ccfab693e9d83acd36d764d076f4f41ceaeab208be00f886a3", c.tampered=false, c.leaf_count=4;
MATCH (m:Model {id:"qwen/qwen3-32b"}),(c:CustodyRoot {model_id:"qwen/qwen3-32b"}) MERGE (m)-[:HAS_CUSTODY]->(c);
MERGE (c:CustodyRoot {model_id:"meta-llama/llama-3.3-70b-instruct"}) SET c.root_sha256="debd569e061140bd8f57dbaac108da8ea445cde302054601e29b0f05c3abf5eb", c.tampered=false, c.leaf_count=4;
MATCH (m:Model {id:"meta-llama/llama-3.3-70b-instruct"}),(c:CustodyRoot {model_id:"meta-llama/llama-3.3-70b-instruct"}) MERGE (m)-[:HAS_CUSTODY]->(c);
MERGE (c:CustodyRoot {model_id:"openai/gpt-oss-120b"}) SET c.root_sha256="3e8a224c1b6c5cc39bba71fe432e5dd1638ca48c2cf24b949e96474696b539ed", c.tampered=false, c.leaf_count=4;
MATCH (m:Model {id:"openai/gpt-oss-120b"}),(c:CustodyRoot {model_id:"openai/gpt-oss-120b"}) MERGE (m)-[:HAS_CUSTODY]->(c);
MERGE (c:CustodyRoot {model_id:"qwen/qwen3-235b-a22b-2507"}) SET c.root_sha256="118c2d92380ac0f8a759f73babdb792950e05508763da545e6396f7db46d7c93", c.tampered=false, c.leaf_count=4;
MATCH (m:Model {id:"qwen/qwen3-235b-a22b-2507"}),(c:CustodyRoot {model_id:"qwen/qwen3-235b-a22b-2507"}) MERGE (m)-[:HAS_CUSTODY]->(c);
MATCH (r:Run {id:"meta_llama_llama_3_3_70b_instruct__doc-water-cycle"}),(c:CustodyRoot {model_id:"meta-llama/llama-3.3-70b-instruct"}) MERGE (r)-[:ROLLS_UP_TO]->(c);
MATCH (r:Run {id:"meta_llama_llama_3_2_1b_instruct__doc-photosynthesis"}),(c:CustodyRoot {model_id:"meta-llama/llama-3.2-1b-instruct"}) MERGE (r)-[:ROLLS_UP_TO]->(c);
MATCH (r:Run {id:"qwen_qwen3_8b__doc-photosynthesis"}),(c:CustodyRoot {model_id:"qwen/qwen3-8b"}) MERGE (r)-[:ROLLS_UP_TO]->(c);
MATCH (r:Run {id:"meta_llama_llama_3_2_1b_instruct__doc-water-cycle"}),(c:CustodyRoot {model_id:"meta-llama/llama-3.2-1b-instruct"}) MERGE (r)-[:ROLLS_UP_TO]->(c);
MATCH (r:Run {id:"qwen_qwen3_8b__doc-water-cycle"}),(c:CustodyRoot {model_id:"qwen/qwen3-8b"}) MERGE (r)-[:ROLLS_UP_TO]->(c);
MATCH (r:Run {id:"meta_llama_llama_3_1_8b_instruct__doc-water-cycle"}),(c:CustodyRoot {model_id:"meta-llama/llama-3.1-8b-instruct"}) MERGE (r)-[:ROLLS_UP_TO]->(c);
MATCH (r:Run {id:"meta_llama_llama_3_1_8b_instruct__doc-photosynthesis"}),(c:CustodyRoot {model_id:"meta-llama/llama-3.1-8b-instruct"}) MERGE (r)-[:ROLLS_UP_TO]->(c);
MATCH (r:Run {id:"meta_llama_llama_3_2_3b_instruct__doc-photosynthesis"}),(c:CustodyRoot {model_id:"meta-llama/llama-3.2-3b-instruct"}) MERGE (r)-[:ROLLS_UP_TO]->(c);
MATCH (r:Run {id:"openai_gpt_oss_20b__doc-photosynthesis"}),(c:CustodyRoot {model_id:"openai/gpt-oss-20b"}) MERGE (r)-[:ROLLS_UP_TO]->(c);
MATCH (r:Run {id:"meta_llama_llama_3_2_3b_instruct__doc-water-cycle"}),(c:CustodyRoot {model_id:"meta-llama/llama-3.2-3b-instruct"}) MERGE (r)-[:ROLLS_UP_TO]->(c);
MATCH (r:Run {id:"openai_gpt_oss_20b__doc-water-cycle"}),(c:CustodyRoot {model_id:"openai/gpt-oss-20b"}) MERGE (r)-[:ROLLS_UP_TO]->(c);
MATCH (r:Run {id:"microsoft_phi_4__doc-water-cycle"}),(c:CustodyRoot {model_id:"microsoft/phi-4"}) MERGE (r)-[:ROLLS_UP_TO]->(c);
MATCH (r:Run {id:"openai_gpt_oss_120b__doc-photosynthesis"}),(c:CustodyRoot {model_id:"openai/gpt-oss-120b"}) MERGE (r)-[:ROLLS_UP_TO]->(c);
MATCH (r:Run {id:"qwen_qwen3_14b__doc-photosynthesis"}),(c:CustodyRoot {model_id:"qwen/qwen3-14b"}) MERGE (r)-[:ROLLS_UP_TO]->(c);
MATCH (r:Run {id:"google_gemma_3_27b_it__doc-photosynthesis"}),(c:CustodyRoot {model_id:"google/gemma-3-27b-it"}) MERGE (r)-[:ROLLS_UP_TO]->(c);
MATCH (r:Run {id:"qwen_qwen3_14b__doc-water-cycle"}),(c:CustodyRoot {model_id:"qwen/qwen3-14b"}) MERGE (r)-[:ROLLS_UP_TO]->(c);
MATCH (r:Run {id:"google_gemma_3_27b_it__doc-water-cycle"}),(c:CustodyRoot {model_id:"google/gemma-3-27b-it"}) MERGE (r)-[:ROLLS_UP_TO]->(c);
MATCH (r:Run {id:"microsoft_phi_4__doc-photosynthesis"}),(c:CustodyRoot {model_id:"microsoft/phi-4"}) MERGE (r)-[:ROLLS_UP_TO]->(c);
MATCH (r:Run {id:"qwen_qwen3_32b__doc-water-cycle"}),(c:CustodyRoot {model_id:"qwen/qwen3-32b"}) MERGE (r)-[:ROLLS_UP_TO]->(c);
MATCH (r:Run {id:"qwen_qwen3_32b__doc-photosynthesis"}),(c:CustodyRoot {model_id:"qwen/qwen3-32b"}) MERGE (r)-[:ROLLS_UP_TO]->(c);
MATCH (r:Run {id:"meta_llama_llama_3_3_70b_instruct__doc-photosynthesis"}),(c:CustodyRoot {model_id:"meta-llama/llama-3.3-70b-instruct"}) MERGE (r)-[:ROLLS_UP_TO]->(c);
MATCH (r:Run {id:"qwen_qwen3_235b_a22b_2507__doc-water-cycle"}),(c:CustodyRoot {model_id:"qwen/qwen3-235b-a22b-2507"}) MERGE (r)-[:ROLLS_UP_TO]->(c);
MATCH (r:Run {id:"openai_gpt_oss_120b__doc-water-cycle"}),(c:CustodyRoot {model_id:"openai/gpt-oss-120b"}) MERGE (r)-[:ROLLS_UP_TO]->(c);
MATCH (r:Run {id:"qwen_qwen3_235b_a22b_2507__doc-photosynthesis"}),(c:CustodyRoot {model_id:"qwen/qwen3-235b-a22b-2507"}) MERGE (r)-[:ROLLS_UP_TO]->(c);
MERGE (x:Decision {id:"ceiling"}) SET x.kind="verdict", x.label="Custody proves provenance of the recorded run — not correctness, not reproducibility. An LLM verdict is a signal, never a custody proof.";
MERGE (x:Decision {id:"commit-floor"}) SET x.kind="commitment", x.label="Pass bar fixed BEFORE running: precision ≥ 0.80 AND recall ≥ 0.75";
MERGE (x:Decision {id:"dec-chosen"}) SET x.kind="decision", x.label="Selected google/gemma-3-27b-it — cheapest passing model on this corpus";
MERGE (x:Decision {id:"dec-rule"}) SET x.kind="decision", x.label="Trusted model = the cheapest model that clears the pass bar";
MERGE (x:Decision {id:"learn-json"}) SET x.kind="learning", x.label="The 70B Llama emitted invalid JSON on 1 of 2 docs — unusable by an automated pipeline";
MERGE (x:Decision {id:"learn-precision"}) SET x.kind="learning", x.label="Every model that returned valid output scored 100% precision — no ungrounded spans survived";
MERGE (x:Decision {id:"learn-size"}) SET x.kind="learning", x.label="Model size did NOT predict recall: 27B Gemma (0.9375) beat the 70B and 120B models";
MATCH (x:Decision {id:"dec-chosen"}),(m:Model {id:"google/gemma-3-27b-it"}) MERGE (x)-[:SELECTED]->(m);
MERGE (z:Citation {doi:"10.5281/zenodo.21210575"}) SET z.title="Fractal Custody Objects: route-comparable chain-of-custody for deterministic computational biology and AI-agent provenance";
MATCH (x:Decision {id:"ceiling"}),(z:Citation {doi:"10.5281/zenodo.21210575"}) MERGE (x)-[:CITES]->(z);
